version: '3'
services:
  web:
    container_name: file_upload_vulnerabilities
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - ./.docker/000-default:/etc/apache2/sites-available/000-default
    ports:
      - 9001:80